spring.application.name=Monpa

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/monpa
spring.datasource.username=root
spring.datasource.password=Samklephvx.1

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080

jwt.secret=8f9b7a2c1d4e6f8a9b1c3d5e7f9a2b4c6d8e1f3a5b7c9d1e3f5a7b9c1d3e5f7